export default {
  FETCH_BOARDS_REQUEST: 'FETCH_BOARDS_REQUEST',
  FETCH_BOARDS_SUCCESS: 'FETCH_BOARDS_SUCCESS',
  FETCH_BOARDS_FAILURE: 'FETCH_BOARDS_FAILURE',
  FETCH_BOARD_REQUEST: 'FETCH_BOARD_REQUEST',
  FETCH_BOARD_SUCCESS: 'FETCH_BOARD_SUCCESS',
  FETCH_BOARD_FAILURE: 'FETCH_BOARD_FAILURE',
  FETCH_ATTATCHMENTS_SUCCESS: 'FETCH_ATTATCHMENTS_SUCCESS',
  SAVE_BOARD_REQUEST: 'SAVE_BOARD_REQUEST',
  SAVE_BOARD_SUCCESS: 'SAVE_BOARD_SUCCESS',
  SAVE_BOARD_FAILURE: 'SAVE_BOARD_FAILURE'
};
